- name: Creating elasticache_subnet_group
  elasticache_subnet_group:
    state: present
    name: "{{ env.name }}{{ cluster.name }}"
    description: "{{ name }} Subnet Group"
    subnets:
      - "{{ ec2_vpc.subnets[0].id }}"
      - "{{ ec2_vpc.subnets[1].id }}"
  register: elasticache_subnet_group
  
- name: Debug elasticache_subnet_group
  debug:
    var: elasticache_subnet_group

- name: Creating elasticache Redis server
  elasticache:
    name: "{{ env.name }}{{ cluster.name }}red"
    state: "{{ redis.state }}"
    engine: redis
    node_type: "{{ redis.node_type }}"
    num_nodes: "{{ redis.num_nodes }}"
    cache_port: 6379
    # try to disable
    cache_engine_version: 2.8.24
    # FIX use elasticache_subnet_group var
    cache_subnet_group: "{{ env.name }}{{ cluster.name }}"
    security_group_ids:
      - "{{ redis_sg_id }}"
  register: redis

- name: Debug redis
  debug:
    var: redis

- name: Debug redis endpoint
  debug:
    var: redis.elasticache.data.CacheNodes[0].Endpoint.Address
