- name: Creating elasticache Redis server
  elasticache:
    name: "{{ name }}red"
    state: present
    engine: redis
    node_type: "{{ redis.node_type }}"
    num_nodes: "{{ redis.num_nodes }}"
    cache_port: 6379
    # try to disable
    cache_engine_version: 2.8.24
    cache_subnet_group: "{{ name }}"
  register: redis

- name: Debug redis
  debug:
    var: redis

- name: Debug redis endpoint
  debug:
    var: redis.elasticache.data.CacheNodes[0].Endpoint.Address
