---
- name: Create /var/www/html
  file:
    path: /var/www/html
    state: directory
    
- name: yum install nginx
  yum: 
    name: 'http://nginx.org/packages/centos/6/x86_64/RPMS/nginx-1.10.1-1.el6.ngx.x86_64.rpm'
    state: present

- name: Remove nginx defaults
  file: 
    path: "/etc/nginx/conf.d/{{ item }}"
    state: absent
  with_items:
    - default.conf
    - php-fpm.conf
    - php-fpm.conf-5.6

#- name: Copy nginx.conf
#  template: 
#    dest: '/etc/nginx/nginx.conf'
#    src: 'nginx.conf'
#    owner: root 
#    group: root 
#    mode: 0644
#  notify:
#    - reload nginx
        
- name: Copy nginx configs
  template: 
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    src: "conf.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ websites }}"
  notify: 
    - reload nginx

- service: 
    name: nginx
    state: started
    enabled: yes
