# Dependencies:
  # {{ name }} is defined in vars
  # {{ vpc_id, vpc_cidr_block }} depend on role get_facts
  
- name: Creating rds_subnet_group
  rds_subnet_group:
    state: present
    name: "{{ name }}rsg"
    description: "{{ name }} Subnet Group"
    subnets: "{{ private_subnets }}"
  register: rds_subnet_group

- name: Creating Security Group for RDS
  ec2_group:
    name: "{{ name }}rds"
    description: "{{ name }}rds"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: "{{ vpc_cidr_block }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: ec2_sg_rds

- name: Creating RDS instance
  rds:
    command: create
    instance_name: "{{ name }}dbm01"
    db_engine: "{{ rds.db_engine }}"
    size: "{{ rds.size }}"
    instance_type: "{{ rds.instance_type }}"
    # FIX: use username and password from vault
    username: "{{ rds.mysqlroot }}"
    password: "{{ rds.mysqlroot_password }}"
    subnet: "{{ name }}rsg"
    vpc_security_groups: "{{ ec2_sg_rds.group_id }}"
    tags:
      Name: "{{ name }}dbm01"
      env: "{{ env.name }}"
      cluster: "{{ cluster.name }}"
    wait: yes
    wait_timeout: 600
  register: rds_instance

- name: Debug rds
  debug:
    var: rds_instance

#- name: Write the RDS facts/values to the file rds_info.yml inside the project directory
#  shell: |
#    echo "db_hostname: {{ rds.instance.endpoint }}" > rds_info.yml
#    echo "db_name: {{ rds_db_name }}" >> rds_info.yml
#    echo "db_username: {{ rds_db_username }}" >> rds_info.yml
#    echo "db_password: {{ rds_db_password }}" >> rds_info.yml
