- name: Creating Security Group
  ec2_group:
    name: "{{ name }}rds"
    description: "{{ name }}rds"
    vpc_id: "{{ vpc.vpc_id }}"
    rules:
      - proto: tcp
        from_port: 3306
        to_port: 3306
#        group_name: default
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: ec2sg

- name: Debug Security Group
  debug:
    var: ec2sg
        
- name: Creating RDS
  rds:
    command: create
    instance_name: "{{ name }}dbm01"
    db_engine: "{{ rds.db_engine }}"
    size: "{{ rds.size }}"
    instance_type: "{{ rds.instance_type }}"
    username: "{{ rds.username }}"
    password: SuperStrongPassword
    # rds_subnet_group
    subnet: "{{ name }}"
    vpc_security_groups: "{{ ec2sg.group_id }}" 
    tags:
      env: "{{ env.name }}"
      cluster: "{{ cluster.name }}"
    wait: yes
    wait_timeout: 600
  register: rds_instance

- name: Debug rds
  debug:
    var: rds_instance

#- name: Write the RDS facts/values to the file rds_info.yml inside the project directory
#  shell: |
#    echo "db_hostname: {{ rds.instance.endpoint }}" > rds_info.yml
#    echo "db_name: {{ rds_db_name }}" >> rds_info.yml
#    echo "db_username: {{ rds_db_username }}" >> rds_info.yml
#    echo "db_password: {{ rds_db_password }}" >> rds_info.yml
