- name: Playbook to deploy Wordpress
  hosts: tag_Name_devbrdweb
  gather_facts: true
  become: yes
  vars:
#    cluster_name: broadcast
    websites:
      - name: cityline
        root: /var/www/html/cityline
#      - name: citytv
  roles:
#    - create_users
    - php
    - nginx

