- name: Playbook to install Flocker
  remote_user: ubuntu
  hosts: tag_Flocker_true
  gather_facts: true
#  vars:
#    node_list: []
#    cluster_name: mycluster
  roles:
    - role: flocker
      become: yes

- name: Playbook to generate certs for Flocker
  remote_user: ubuntu
  hosts: tag_flocker_manager
  gather_facts: true
  vars:
    cluster_name: mycluster
  roles:
    - role: flocker-certs
      become: yes

      
- name: Copy certs to the nodes
  remote_user: ubuntu
  hosts: tag_flocker_node
  gather_facts: true
  tasks:
    - copy:
        src: /tmp/cluster.crt
        dest: /etc/flocker/cluster.crt

        
- name: Generate certs for the nodes
  remote_user: ubuntu
  hosts: tag_flocker_manager
  gather_facts: true
  tasks:
    - name: flocker-ca create-node-certificate
      command: flocker-ca create-node-certificate
      args:
        chdir: /etc/flocker
#        creates: /etc/flocker/*-*-*.crt
      register: node_cert
      with_items: "{{ groups['tag_flocker_node'] }}"

    - name: Debug node_cert
      debug:
        var: node_cert

    - name: set fact for node cert
      set_fact:
        cert_id: "{{ item.stdout[item.stdout.index('Created'):item.stdout.index('.')].split(' ')[1] }}"
      with_items: "{{ node_cert.results }}"
        
    - name: Node certificate debug
      debug:
        var: cert_id

#    - name: rename cert_id to node_crt
#      command: mv "{{ cert_id }}.{{ item }}" "node.{{ item }}"
#      args:
#        chdir: /etc/flocker
#        creates: "/etc/flocker/node.{{ item }}"
#      with_items: "{{ cert_id }}"
