- name: Playbook to install Flocker
  remote_user: ubuntu
  hosts: tag_Flocker_true
  gather_facts: true
#  vars:
#    node_list: []
#    cluster_name: mycluster
  roles:
    - role: flocker
      become: yes

- name: Playbook to generate certs for Flocker
  remote_user: ubuntu
  hosts: tag_flocker_manager
  gather_facts: true
  vars:
    cluster_name: mycluster
  roles:
    - role: flocker-certs
      become: yes
     
- name: Copy certs to the nodes
  remote_user: ubuntu
  hosts: tag_flocker_node
  gather_facts: true
  tasks:
    - copy:
        src: /tmp/cluster.crt
        dest: /etc/flocker/cluster.crt
