- name: Playbook to install Flocker
  remote_user: ubuntu
  hosts: tag_Flocker_true
  gather_facts: true
#  vars:
#    cluster_name: mycluster
  roles:
    - role: flocker
      become: yes

- name: Playbook to generate certs for Flocker
  remote_user: ubuntu
  hosts: tag_flocker_manager
  gather_facts: true
  vars:
    cluster_name: mycluster
  tasks:
    - name: Generate cluster certificate
      command: flocker-ca initialize "{{ cluster_name }}"
      args:
        chdir: /etc/flocker
        creates: /etc/flocker/cluster.crt
                    
 # roles:
 #   - role: flocker
 #     become: yes

      
