- name: Creating Security Group
  ec2_group:
    name: "{{ item.name }}-{{ ec2_vpc.vpc_id }}"
    description: "{{ item.name }}"
    vpc_id: "{{ ec2_vpc.vpc_id }}"
    rules:
      - proto: "{{ item.proto }}"
        from_port: "{{ item.port }}"
        to_port: "{{ item.port }}"
        cidr_ip: "{{ item.cidr_ip }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  with_items: "{{ security_group }}"
  register: ec2_sg

- name: Debug Security Group
  debug:
    var: ec2_sg

- name: Set sg_id as facts
  set_fact:
    "{{ item.item.name }}_sg_id": "{{ item.group_id}}"
  with_items: "{{ ec2_sg.results }}"
