#ruby
#wget
#wget https://aws-codedeploy-us-west-2.s3.amazonaws.com/latest/install
#chmod +x ./install
#sudo ./install auto

#service codedeploy-agent status

- name: Get Instance Metadata
  action: ec2_facts

- name: Get CodeDeploy
  command: wget https://aws-codedeploy-us-west-2.s3.amazonaws.com/latest/install
  
- name: Codedeploy Install Binary
  file:
    state: file
    path: /home/ec2-user/install
    mode: 0755
    
- name: Codedeploy Install
  become: true
  command: /home/ec2-user/install auto
