- name: Create security group
  ec2_group:
    name: "jump-{{ vpc.id }}"
    description: "jump"
    vpc_id: "{{ vpc.id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: ec2sg

- name: Debug ec2sg
  debug:
    var: ec2sg

- name: Provision ec2 instance
  ec2:
    image: "{{ jump.source_ami }}"
    instance_type: "{{ jump.instance_type }}"
    key_name: "{{ jump.key_name }}"
    vpc_subnet_id: 'subnet-3080ec46'
#    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    group_id: "{{ ec2sg.group_id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "jump-{{ vpc.id }}"
      StopInstanceAtNight: "True"
    count_tag:
      Name: "jump-{{ vpc.id }}"
    exact_count: 1
    wait: yes
  register: jump

- name: Debug jump
  debug:
    var: jump
  
#- name: Add new instance to host group
#  add_host: 
#    hostname: "{{ item.public_ip }}" 
#    groupname: jump
#  with_items: "{{ jump.tagged_instances }}"

#- name: Wait for SSH to come up
#  wait_for: 
#    host: "{{ item.public_dns_name }}" 
#    port: 22 
#    state: started
#  with_items: "{{ jump.tagged_instances }}"

