- name: Create security group
  ec2_group:
    name: jump
    description: "jump"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: ec2sg

- name: Debug ec2sg
  debug:
    var: ec2sg
  
- name: Provision ec2 instance
  ec2:
    group_id: "{{ ec2sg.group_id }}"
    image: "{{ jump.source_ami }}"
    instance_type: "{{ jump.instance_type }}"
    key_name: "{{ jump.key_name }}"
    instance_tags:
      Name: jump
    count_tag:
      Name: jump
    exact_count: 1
    wait: yes
  register: jump

- name: Add new instance to host group
  add_host: 
    hostname: "{{ item.public_ip }}" 
    groupname: jump
  with_items: jump.tagged_instances

- name: Wait for SSH to come up
  wait_for: 
    host: "{{ item.public_dns_name }}" 
    port: 22 
    state: started
  with_items: jump.tagged_instances

#- hosts: jump
#  user: ec2-user
#  gather_facts: yes
#  roles:
#    - role: nginx
#      become: yes
#    - role: deploy
