#    health_check_period: 300
#    health_check_type: 'EC2'
#    health_check_type: 'ELB'

- name: Create LB
  ec2_elb_lb:
    name: "{{ env.name }}{{ cluster.name }}elb"
    state: present
    zones:
      - "{{ ec_vpc.subnets[0].az }}"
      - "{{ ec_vpc.subnets[1].az }}"
    cross_az_load_balancing: yes
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    idle_timeout: 60
  register: ec2_elb

- name: Debug ec2elb
  debug:
    var: ec2_elb

- name: Create security group
  ec2_group:
    name: "{{ env.name }}{{ cluster.name }}elb"
    description: "Allow access to 80 port on web nodes from ELB"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        group_id: "{{ ec2_elb.elb.security_group_ids[0] }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: ec2_elb_sg

# then use ec2_elb_sg for sg on web nodes
