#    health_check_period: 300
#    health_check_type: 'EC2'
#    health_check_type: 'ELB'

- name: Create LB
  ec2_elb_lb:
    name: "{{ name }}elb"
    state: present
    zones:
      - "{{ vpc.subnets[0].az }}"
      - "{{ vpc.subnets[1].az }}"
    cross_az_load_balancing: yes
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    idle_timeout: 60
  register: ec2elb

- name: Debug ec2elb
  debug:
    var: ec2elb

- name: Create security group
  ec2_group:
    name: "{{ app_name }}-{{ env }}-{{ service }}"
    description: "Allow access to {{ app_name }} {{ env }} {{ service }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        group_name: default
#        group_id: "{{ vpc.default_security_group_id }}"
      - proto: tcp
        from_port: 80
        to_port: 80
        group_id: "{{ ec2elb.elb.security_group_ids[0] }}"
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
  register: ec2sg


