- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - software-properties-common
    
- name: Add clusterhq repo
  apt_repository:
    repo: "deb https://clusterhq-archive.s3.amazonaws.com/ubuntu/{{ ansible_distribution_version }}/$(ARCH) /"
    state: present
    
- name: Copy repo config
  copy:
    src: buildbot-700
    dest: /etc/apt/preferences.d/buildbot-700
    owner: root
    mode: 0644

- name: Install clusterhq-flocker pakages
  apt:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: yes
  with_items:
    - clusterhq-flocker-cli
    - clusterhq-flocker-node
    - clusterhq-flocker-docker-plugin
    
- name: Create flocker configs dir
  file:
    path: /etc/flocker
    state: directory
    mode: 0750

#- name: set fact
#  set_fact:
#    foo_item: "{{ item }}"
#  with_items:
#    - four
#    - five
#    - six
#  register: foo_result
  
- name: make a list
  set_fact:
    foo: "{{ ec2_private_dns_name | list }}"
  
- debug:
    var: foo
      
#- name: Create list with private dns names
#  local_action:
#    add_host:
#      hostname: "{{item}}"
#      groupname: flocker_nodes
#  with_items: "{{ ec2_private_dns_name }}"
