- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - software-properties-common

- name: Add clusterhq repo
  apt_repository:
    repo: "deb https://clusterhq-archive.s3.amazonaws.com/ubuntu/{{ ansible_distribution_version }}/$(ARCH) /"
    state: present

- name: Copy repo config
  copy:
    src: buildbot-700
    dest: /etc/apt/preferences.d/buildbot-700
    owner: root
    mode: 0644
    
- name: Install clusterhq-flocker pakages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - clusterhq-flocker-node
    - clusterhq-flocker-docker-plugin

#- name: Creating Security Group
#  ec2_group:
#    name: "{{ item.name }}-{{ vpc.vpc_id }}"
#    description: "{{ item.name }}"
#    vpc_id: "{{ vpc.vpc_id }}"
#    rules:
#      - proto: "{{ item.proto }}"
#        from_port: "{{ item.port }}"
#        to_port: "{{ item.port }}"
#        cidr_ip: "{{ item.cidr_ip }}"
#    rules_egress:
#      - proto: all
#        cidr_ip: 0.0.0.0/0
#  with_items: "{{ flocker.security_group }}"
#  register: ec2_security_group

#- name: Debug Security Group
#  debug:
#    var: ec2_security_group

