- name: set fact manager
  set_fact:
    flocker_control_node_ip: "{{ groups['tag_flocker_manager'][0] }}"

- name: get fact manager
  debug:
    var: flocker_control_node_ip

- name: Copy agent.yml no the nodes
  template:
    src: agent.yml
    dest: /etc/flocker/agent.yml

