- name: Generate cluster certificate
  command: flocker-ca initialize "{{ cluster_name }}"
  args:
    chdir: /etc/flocker
    creates: /etc/flocker/cluster.crt

- name: Generate auth certs for control service and nodes
  command: flocker-ca create-control-certificate "{{ ec2_private_dns_name }}"
  args:
    chdir: /etc/flocker
    creates: "/etc/flocker/control-{{ ec2_private_dns_name }}.crt"

- name: Rename auth certs for control service and nodes
  command: mv "control-{{ ec2_private_dns_name }}.{{ item }}" "control-service.{{ item }}"
  args:
    chdir: /etc/flocker
    creates: "/etc/flocker/control-service.{{ item }}"
  with_items:
    - crt
    - key

- name: Set mode 0600 on control-service.key
  file:
    path: /etc/flocker/control-service.key
    mode: 0600
    
- name: Copy cluster.crt to ansible host
  fetch:
    src: /etc/flocker/cluster.crt
    dest: /tmp/cluster.crt
    flat: yes

- name: Generate API certs
  command: flocker-ca create-api-certificate "{{ api_client_name }}"
  args:
    chdir: /etc/flocker
    creates: "{{ api_client_name }}.crt"

- name: Generate Docker Plugin certs
  command: flocker-ca create-api-certificate plugin
  args:
    chdir: /etc/flocker
    creates: plugin.crt

- name: Fetch plugin.crt to ansible host
  fetch:
    src: "/etc/flocker/plugin.{{ item }}"
    dest: "/tmp/plugin.{{ item }}"
    flat: yes
  with_items:
    - key
    - crt
#- name: set fact groups
#  set_fact:
#    node_list: "{{ groups['tag_Flocker_true'] }}"
    
#- name: debug groups
#  debug:
#    var: node_list
    
#- name: Copy Remote-To-Remote (from serverA to serverB)
#  synchronize:
#    src: /etc/flocker/cluster.crt
#    dest: /etc/flocker/cluster.crt
#  become: yes
#  delegate_to: "{{ item }}"
#  with_items: "{{ node_list }}"
