- name: Provision ec2 instances for Web nodes
  ec2:
    vpc_subnet_id: "{{ vpc_subnets[0] }}"
    group_id: "{{ http_sg_id }}"
    image: "{{ web.image }}"
    instance_type: "{{ web.instance_type }}"
    key_name: "{{ web.key_name }}"
    instance_tags:
      Name: "{{ env.name }}{{ cluster.name }}web"
      Env: "{{ env.name }}"
    count_tag:
      Name: "{{ env.name }}{{ cluster.name }}web"
    exact_count: 2
    wait: true
#  with_items: "{{ vpc_subnets }}"
  register: ec2_web

- name: Debug ec2_web
  debug:
    var: ec2_web
  
#- name: Add new instance to host group
#  add_host: 
#    hostname: "{{ item.private_ip }}" 
#    groupname: ec2_web_instances
#  with_items: ec2_web.tagged_instances

- name: Wait for SSH to come up
  wait_for: 
    host: "{{ item.private_ip }}" 
    port: 22 
    delay: 60 
    state: started
  with_items: ec2_web.tagged_instances
