- name: Creating Security Group for Web Nodes
  ec2_group:
    name: "{{ env.name }}{{ cluster.name }}web"
    description: "{{ env.name }}{{ cluster.name }}web"
    vpc_id: "{{ ec2_vpc.vpc_id }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "{{ ec2_vpc.vpc.cidr_block }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: ec2_sg_web

- name: Debug Security Group for Web Nodes
  debug:
    var: ec2_sg_web

- name: Provision ec2 instances for Web nodes
  ec2:
    # FIX: create instances in differrent subnets
    vpc_subnet_id: "{{ private_vpc_subnets[0] }}"
    group_id: "{{ ec2_sg_web.group_id }}"
    image: "{{ web.image }}"
    instance_type: "{{ web.instance_type }}"
    key_name: "{{ web.key_name }}"
    instance_tags:
      Name: "{{ env.name }}{{ cluster.name }}web"
      Env: "{{ env.name }}"
    count_tag:
      Name: "{{ env.name }}{{ cluster.name }}web"
    exact_count: 2
    wait: true
#  with_items: "{{ private_vpc_subnets }}"
  register: ec2_web

- name: Debug ec2_web
  debug:
    var: ec2_web
  
- name: Wait for SSH to come up
  wait_for: 
    host: "{{ item.private_ip }}" 
    port: 22 
    delay: 60 
    state: started
  with_items: "{{ ec2_web.tagged_instances }}"
