# Full creation example with subnets and optional availability zones.
# The absence or presence of subnets deletes or creates them respectively.
- name: Creating VPC
  ec2_vpc:
    state: "{{ vpc.state }}"
    region: "{{ vpc.region }}"
    cidr_block: "{{ vpc.cidr_block }}"
    resource_tags: { "Name":"{{ env.name }}{{ cluster.name }}vpc" }
    subnets: "{{ vpc.subnets }}"
    internet_gateway: True
    route_tables: "{{ vpc.route_tables }}"
  register: ec2_vpc

- name: Debug ec2_vpc
  debug:
    var: ec2_vpc

- name: set fact vpc_subnets
  set_fact:
    vpc_subnets:
      - "{{ ec2_vpc.subnets[0].id }}"
      - "{{ ec2_vpc.subnets[1].id }}"

- name: debug vpc_subnets
  debug:
    var: vpc_subnets
