- name: Create groups
  group: 
    name: "{{ item.name }}"
    state: present
  with_items: "{{ websites }}"

- name: Create users
  user: 
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    state: present
  with_items: "{{ websites }}"

- name: Install php packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php56-fpm
    - php56-soap
    - php56-mysqlnd
    - php56-pdo

- name: Install php packages v2
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php56-mbstring
    - php56-opcache

- name: Install php packages v3
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php56-pecl-redis
    - php-pear
    - php56-pecl-igbinary

- name: Install php packages v4
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php56-gd
    - libXpm
    - t1lib

- name: Install php packages v5
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php56-mcrypt
    - libmcrypt
    - libtool-ltdl

#- name: Copy php-fpm-5.6.conf
#  template:
#    dest: /etc/php-fpm-5.6.conf
#    src: php-fpm-5.6.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#    - restart php-fpm

- name: Remove php-fpm defaults
  file: 
    path: "/etc/alternatives/php-fpm.d/www.conf"
    state: absent

- name: Copy php-fpm config 
  template: 
    dest: "/etc/alternatives/php-fpm.d/{{ item.name }}.conf"
    src: "php-fpm.d/template.conf"
    owner: root
    group: root 
    mode: 0644
  with_items: "{{ websites }}"
  notify: 
    - restart php-fpm

- service: 
    name: php-fpm-5.6
    enabled: yes
    state: started
